name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH key
        run: |
          install -m 700 -d ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # - name: Trust host key
      #  run: |
      #    ssh-keyscan "${SSH_HOST}" >> ~/.ssh/known_hosts

      - name: Ensure destination exists
        run: |
          ssh-keyscan -t ed25519,rsa 158.160.194.102   >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa davmxxx@158.160.194.102 "mkdir -p /opt/speedy-ship-base"

      - name: Copy files via rsync (overwrite; prune extras)
        run: |
          rsync -az --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "node_modules/***" \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" \
            --rsync-path="sudo rsync" \
            ./ "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/speedy-ship-base/"

      #- name: delete old files
      #  run: |
      #    sudo rm -rf /opt/speedy-ship-base/*

      # - name: Copy files to server
        

      - name: Restart site service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/speedy-ship-base
            sudo npm install 
            sudo npm run build
            sudo chown -R www-data:www-data /opt/speedy-ship-base 
